title: itProger Learning Django 
author: Eugene Zuev
theme: jekyll-theme-cayman
branch: "gh-pages" #  use "master" for user page or "gh-pages" for project pages
exclude:
 - .gitignore
paginate_path: "/about/page:num/"

navbar-links:
  About Me: "https://zhekazuev.github.io"
  Resources:
    # - Check Design: "https://zhekazuev.github.io/emonitoring-poczta-polska/"
    # - Heroku: "https://emonitoring-poczta-polska.herokuapp.com/"
  Author's home: "https://github.com/zhekazuev"

social-network-links:
  email: "zhekazuev@gmail.com"
  github: zhekazuev
  linkedin: zhekazuev